version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: $uid
        GROUP_ID: $gid
    image: php
    user: "${uid}:${gid}"
    environment:
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=project"
      XDEBUG_CONFIG: "client_host=10.244.0.1"
      SSH_AUTH_SOCK: "/ssh-agent"
    volumes:
      - ${HOME}/.composer:/.composer
      - ./:/var/www
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${HOME}/.ssh:/home/www-data/.ssh:ro
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
    networks:
      - project
  runner:
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_ID: $uid
        GROUP_ID: $gid
    image: php
    command: php artisan queue:listen
    depends_on:
      - db
      - redis
    environment:
      #PHP_IDE_CONFIG: "serverName=project"
      #XDEBUG_CONFIG: "client_host=10.244.0.1"
      XDEBUG_CONFIG: "client_host=172.17.0.1"
    volumes:
      - ${HOME}/.composer:/.composer
      - ./:/var/www
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - project
  redis:
    image: redis
    networks:
      - project
  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: 666Admin!!!
      MYSQL_USER: app
      MYSQL_PASSWORD: 666Admin!!!
    ports:
      - 13306:3306
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - project
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - project
  mail:
    image: maildev/maildev
    networks:
      - project
    ports:
      - 8025:80
  node:
    image: node:14
    user: "${uid}:${gid}"
    restart: unless-stopped
    ports:
        - 3000:3000  # Browsersync proxy
        - 3001:3001  # Browsersync websocket
    volumes:
        - ./:/var/www  # Persist packages
    networks:
        - project
    working_dir: /var/www
    command: sh -c "npm install && npm run watch"
    
networks:
  project:
    driver: bridge
volumes:
  db: